name: reading-between-tokens
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - pytorch
  - pytorch-cuda==12.4
  - pydantic==2.12.5
  - deepspeed==0.17.6
  - transformers==4.57.3
  - scikit-learn==1.8.0
  - matplotlib==3.10.8
  - pandas==2.3.3
  - scipy==1.16.3
  - pip==25.3
  - pip:
      - transformer-lens==2.16.1
